# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(default=None, upload_to='episodes/'),
            preserve_default=False,
        ),
    ]
