# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_episode_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
